version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: gluetun_server_1
      APP_PORT: 8000
    container_name: gluetun_app_proxy_1
  app:
    image: qmcgaw/gluetun
    container_name: gluetun_server_1
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    user: '1000:1000'
    volumes:
      - ${UMBREL_ROOT}/home/Downloads/wg0.conf:/gluetun/wireguard/wg0.conf:ro
    ports:
      - 8000:8000/tcp
      - 1080:1080/tcp
      - 1080:1080/udp
      - 8888:8888/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - SERVER_COUNTRIES="Austria, Belgium, Brazil, Bulgaria, Canada, Czech Republic, Estonia, Germany, Ireland, Japan, Latvia, Netherlands, New Zealand, Norway, Romania, Serbia, Singapore, Spain, Sweden, Switzerland, United Kingdom, United States"
      - HTTPPROXY=on
  socks5:
    image: serjs/go-socks5-proxy
    user: '1000:1000'
    container_name: gluetun_socks5_proxy_1
    network_mode: service:gluetun_server_1
    environment:
      - REQUIRE_AUTH=false
