version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: handbrake_server_1
      APP_PORT: 5800
    container_name: handbrake_app_proxy_1
  server:
    image: >-
      ghcr.io/chuchucharlie/docker-handbrake:master
    container_name: handbrake_server_1
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - /downloads:/storage
      - /downloads/handbrakewatch:/watch
      - /downloads/handbrakeoutput:/output
      - ${APP_DATA_DIR}/data/trash:/trash
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    security_opt:
      - seccomp=unconfined
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
